# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8000138215c4ecf89bd9008bc38e95b53d9b576ac17ec00249eb8eab5ee8ece9aef92854fba20c8b7ddb951f285bb290583fd23c59fc2f4cd99cfa3f8f2f58cd

test:
  secret_key_base: f07e095db76f65a70051b81fe361252a545d5f4b218698d03384d5d046967f3417e3d257c18864b44e216a43581d6fb15f88e8555c552dbd2973b5663094aea3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
